# Generated by Django 3.0.5 on 2020-07-09 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(auto_created=True, verbose_name='auction end date')),
                ('date_start', models.DateTimeField(auto_created=True, verbose_name='auction start date')),
                ('object_id', models.PositiveIntegerField()),
                ('current_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='current winning bid')),
                ('start_bid', models.IntegerField(default=1, verbose_name='starting bid amount')),
                ('reserve_price', models.IntegerField(default=1, verbose_name='reserve price')),
                ('bid_increment', models.IntegerField(blank=True, null=True, verbose_name='minimum incremental bid')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='e.g. Samsung', max_length=50)),
                ('model', models.CharField(help_text='e.g. S20', max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Mint', 'Mint'), ('Boxed', 'Boxed')], default='NEW', max_length=10)),
                ('operating_system', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Windows', 'Windows'), ('Other', 'Other')], max_length=10)),
                ('colour', models.CharField(max_length=50)),
                ('storage_capacity', models.CharField(max_length=25)),
                ('ram', models.CharField(max_length=50, verbose_name='RAM size')),
                ('processor_type', models.CharField(max_length=100)),
                ('processor_speed', models.CharField(help_text='e.g. 2.1GHz', max_length=50)),
                ('camera', models.CharField(help_text='e.g. 20 mega pixels', max_length=50)),
                ('screen_size', models.CharField(help_text='e.g. 5.1 inches', max_length=50)),
                ('screen_type', models.CharField(max_length=100)),
                ('notes', models.TextField(help_text='Any other details that may help describe your phone', max_length=250)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='bid amount')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
            ],
        ),
    ]
