# Generated by Django 2.2 on 2020-04-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='account',
        ),
    ]
