# Generated by Django 3.0.5 on 2020-07-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='view',
            field=models.CharField(default='auction/add-product', max_length=50),
        ),
    ]
