# Generated by Django 3.0.5 on 2020-07-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_category_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='view',
            field=models.CharField(max_length=50),
        ),
    ]
