# Generated by Django 3.0.5 on 2020-07-12 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200712_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='ending_date',
            new_name='ending_date_and_time',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auction_length',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_date_and_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
