# Generated by Django 3.0.5 on 2020-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200624_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_increment',
            field=models.IntegerField(blank=True, null=True, verbose_name='minimum incremental bid'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='reserve price'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_bid',
            field=models.IntegerField(default=1, verbose_name='starting bid amount'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(max_length=20, verbose_name='bid amount'),
        ),
    ]
