# Generated by Django 2.2 on 2020-04-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20200410_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(max_length=500),
        ),
    ]
