# Generated by Django 3.0.5 on 2020-07-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20200712_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='object_id',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='content_type',
        ),
        migrations.AddField(
            model_name='auction',
            name='model_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
