# Generated by Django 2.2 on 2020-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200420_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Mint', 'Mint'), ('Boxed', 'Boxed')], default='NEW', max_length=10),
        ),
    ]
