# Generated by Django 3.0.5 on 2020-07-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200713_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='auction',
            name='ending_date_and_time',
            field=models.DateTimeField(auto_created=True, help_text='Please use the following date and time format: mm/DD/YYYY HH:MM'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_date_and_time',
            field=models.DateTimeField(auto_created=True, help_text='Please use the following date and time format: mm/DD/YYYY HH:MM'),
        ),
        migrations.AlterField(
            model_name='category',
            name='view',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
