# Generated by Django 3.0.5 on 2020-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20200714_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='view',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
