# Generated by Django 3.0.5 on 2020-07-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20200714_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
